### ISSUE TITLE
How uploads work inside a folder

### ISSUE THREAD

**Issue by juanitourquiza** [kartoteket/vue-image-upload-resize#10]
I understand the example but I need to upload the image and I read in the documentation that is used @onUpload and @onComplete. Is there an example or can you tell me how this works?

**Comment by svale** [comment]
@juanitourquiza Apologies for the delayed response! Unfortunately, I'm not sure i understand your question...

The plugin _only_ handles the client (browser) side of the file upload. In your app you would need to attach a suitable logic (typically an API POST call ) to one of the events (preferable @input) that passes the image on to your server backend where it is saved. 

So as a simple example, if `@input="setImage"`, you could use a method like
```js
    setImage: function (file) {

      // either A) save file to a vuex store and take it from there
      this.$store.commit('SET_IMAGE', file)

      // or B) post directly with axios (extremely simplified)
     let formData = new FormData();
     formData.append('file', file);
     axios.post( 'API-ENDPOINT',
       formData,
       {
         headers: { 'Content-Type': 'multipart/form-data' }
       }
     ).then(function(){ console.log('ok!');
    })
    .catch(function(){ console.log('failed!'); });
  },
```
There is a a better and more comprehensive guide on file uploads at https://scotch.io/tutorials/how-to-handle-file-uploads-in-vue-2 

And you might also find some useful pointers on the server-side handling in one of the resources listed on https://www.dropzonejs.com/#server-side-implementation

**Comment by svale** [comment]
Feel free to re-open if there is anything else :-)
