### ISSUE TITLE
Will this uploader work with Vue CLI3 ?

### ISSUE THREAD

**Issue by iToreTS** [kartoteket/vue-image-upload-resize#13]
Hi.
First of all @svale - this looks like an awesome fileuploader component, and is exactly what I was looking for.
I am trying to use this in my Vue CLI3 project, and I can't get it to work...
I have tried different types of configuration, but it will not emit any of the 3 events documented.
So it seems like nothing happens when I select an image, and the standard upload control (in Chrome) shows :" No file chosen "

The markup in DevTools look like this:
```html
<div>
<img width="400" class="img-preview" style="display: none;">
<input id="fileInput" type="file" accept="image/*" capture="environment" class="fileinput">
</div>
```
...and the component looks ok in the Vue-devTools inspector.

My latest atempt looks like this in my view file:
 ```html
<image-uploader :debug="1" :autoRotate="false" outputFormat="string" :preview="true"
              :className="['fileinput', { 'fileinput--loaded' : hasImage }]" capture="environment" 
             @input="setImage">
</image-uploader>
```

An idea of what makes it unresponsive ?
Any other dependencies I need with CLI3 ?

Best regards
iToreTS

**Comment by iToreTS** [comment]
Well, my fault...
It works perfectly ok now.

The issue was that I had another INPUT of type="file" earlier in the view.
When I put the <image-uploader> on top of page or removed the old input control, it worked as expected.

**Comment by iToreTS** [comment]
By the way - the Roadmap and ToDo-list of this component looks great :)

**Comment by svale** [comment]
Hei @iToreTS - Takk for hyggelig tilbakemelding. Beklager at du aldri fikk svar her - jeg så ikke issuet ditt før i dag. Bra det løste seg  :-)
