### ISSUE TITLE
Cannot open photo library

### ISSUE THREAD

**Issue by bestian** [kartoteket/vue-image-upload-resize#17]
on ios, 
when I click the upload image button
it shows only camera, no "photo library" option

**Comment by adapterdigital** [comment]
just remove :capture="capture" from the component

**Comment by adapterdigital** [comment]
Not tested: Maybe you can try setting :capture="false" in view instead of remove the code.

**Comment by svale** [comment]
Thanks @adapterdigital I'll have `false` set as the default value in the next update.

**Comment by svale** [comment]
Resolved in [2.1.1](https://github.com/kartoteket/vue-image-upload-resize/releases/tag/v2.1.1)
