### ISSUE TITLE
Multiple Usage of component on the same page

### ISSUE THREAD

**Issue by enkhtulga** [kartoteket/vue-image-upload-resize#18]
i want to use your component more than one in specific page. When i try to use it as i want, uploaded image replaced preview components image. How can i solve it?

**Comment by enkhtulga** [comment]
I found the solution. In documentation: The ID for the file input, required if more than one instance should be used on the same page. :)

**Comment by enkhtulga** [comment]
Unfortunately, ID prop is not working property.

**Comment by enkhtulga** [comment]
When i try to change ID (input tag style: display none;), css is not working. I write custom css for it. It meant that issue is resolved.

**Comment by enkhtulga** [comment]
Documentation: The ID for the file input, required if more than one instance should be used on the same page.

**Comment by elvisito** [comment]
Please, any example for guide..... I can´t make to work two components on same page.  Where to go ID when two components are used?.  Thanks.
