### ISSUE TITLE
Change the input style

### ISSUE THREAD

**Issue by Steve-Groner** [kartoteket/vue-image-upload-resize#27]
Is there any way to modify the text/icon/button for the tool?  I would like to modify the text to be Capture/Select Photo and NOT show the file name how would I do that?

**Comment by svale** [comment]
Yes,

if I understand you correctly,  that should be possible by hiding the default input markup and including your own through the slot-option.  

Example here: https://codesandbox.io/s/vue-image-upload-and-resize-6ddsw

**Comment by svale** [comment]
I'll close this as there is no new activity.
