### ISSUE TITLE
Nuxt/SSR Support

### ISSUE THREAD

**Issue by atymic** [kartoteket/vue-image-upload-resize#28]
Unfortunately you're not able to use this with nuxt, as trying to load the component results in attempts to access `window` which isn't defined.

I'll investigate further soon :)

**Comment by svale** [comment]
Hi! Your right, this plugin was not written with nuxt in mind. And I've never tested it either. 

That said, I guess in theory it should run if you include it as a client only plugin (what now is called `{mode: client`}) , see https://nuxtjs.org/guide/plugins/#vue-plugins and https://nuxtjs.org/api/configuration-plugins.

If time permits, I'll  have a look at making it universal/ssr friendly.

**Comment by atymic** [comment]
Can confirm that your suggestion works, along with wrapping the actual element in `<no-ssr>` tags.

Maybe just worth a PR to add to the docs?

**Comment by svale** [comment]
Cool! Sure, until we get SSR-readiness built inn, an addition to the docs would be very welcome. 

PS: looks like `<no-ssr>` is being replaced by `<client-only>` (https://nuxtjs.org/api/components-client-only/)

**Comment by atymic** [comment]
Yep, we're on an old version at the moment.
Will PR shortly :)

**Comment by svale** [comment]
PR merged and will be included in next release :)
