### ISSUE TITLE
Exif data not available in setImage

### ISSUE THREAD

**Issue by deepam-github** [kartoteket/vue-image-upload-resize#30]
Hi,

I am using vue-image-upload-resize (version 2.1.2) to resize the files but I lose the exif data. In my 'setImage' function the console.log is displayed as the picture below. Please note that there is Exif data in there. But when the data is used in setImage, its always undefined. It seems that the Exif object does not exist immediately in setImage but is embedded into console later?

![](https://i.stack.imgur.com/Zr2KL.png)

Please help.

Regards
Deepam

**Comment by svale** [comment]
@deepam-github thank yup for your patience!

Could you please check which output format you have set? Exif-data will only be returned if `output` is set to `verbose`, but you should then be returned an object with the  keys `dataUrl`, `info`, `exif`. This is probably also a bit clearer in the latest version (2.2.0), so you might want to update as well.

Note that the exif data is not preserved in the returned image itself (as it is lost in the scaling), so you would only have it available as a js-object in the output. (There is a PR that changes this behaviour but I'm  not sure this will be merged as it introduces a new dependency.)

**Comment by svale** [comment]
I'll close this now as there is no more activity. Feel fre to re-open if needed.
