### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by VictorOnwukwe** [kartoteket/vue-image-upload-resize#32]
It keeps giving the error "Failed to mount component: template or render function not defined."

And I have all dependencies required to load the component.

**Comment by objcow** [comment]
I got that error when I imported and added this component directly to my view component. However, it worked properly when I instead added it globally to my app's main.js. It should work both ways, but this workaround may help you.

**Comment by wanderleypanosso** [comment]
@objcow I'm facing the same issue here and it is not working even with global registration. 

import imageUploader from 'vue-image-upload-resize'

Vue.component('image-uploader', imageUploader)

Is this how you did it?

**Comment by objcow** [comment]
I did:
```
import ImageUploader from "vue-image-upload-resize";
Vue.use(ImageUploader);
```

**Comment by vsirghii** [comment]
I'm also having the same message "Failed to mount component: template or render function not defined." when imported and added this component directly to my view component. Yes global installation works (with Vue.use(ImageUploader);) but that creates a global instance and in my scenario, when I have couple of vue components with ImageUploader on the same page, images are uploaded into first instance only.
Is there any way to register ImageUploader on a vue component, not on the whole app, as usual registration:
<script>
import ImageUploader from "vue-image-upload-resize";
export default {
  name: 'TagImage',
  components: {
    ImageUploader
  }....

**Comment by svale** [comment]
Hi @vsirghii (cc @objcow, @wanderleypanosso, @VictorOnwukwe)

Sorry about this. I somehow messed up how Vue CLI builds for library as target. The new  [2.3 release](https://github.com/kartoteket/vue-image-upload-resize/releases/tag/v2.3.0) should help. 

With this version it is possible to use both initalising as a global plugin (using `Vue.use()`) and local registration inside another component:

```js
export default {
  components: { 
    ImageUploader
  },
  // ...
}

**Comment by vsirghii** [comment]
Awesome Svale .That's a great news. You guys are doing really good job here.
