### ISSUE TITLE
Can't use this module with nuxt js; "Reason: ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by Pranavraut033** [kartoteket/vue-image-upload-resize#50]
Throws the following error when using as a plugin in Nuxt JS.

> Reason: ReferenceError: window is not defined

```js
    !(__WEBPACK_AMD_DEFINE_RESULT__ = (function() {
      return dataURLtoBlob
    }).call(exports, __webpack_require__, exports, module),
        __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__))
  } else {}
})(window)
```

in `~/plugins/image-uploader.js`

```js
import Vue from "vue";
import ImageUploader from "vue-image-upload-resize";

Vue.use(ImageUploader);
```

### Work Around

Using `<client-only>` tag provided by nuxt

```html
<client-only>
  <image-uploader :quality="0.9" :max-width="512" accept="image/*" ... />
</client-only>
```

and registering components locally as

```js
components: {
  ImageUploader: () => import("vue-image-upload-resize")
},
```

**Comment by KerneggerTim** [comment]
Hey @Pranavraut033, there are already instructions in the documentation on how to integrate vue-image-upload-resize in nuxt.js.

1. Create a new file: plugins/vue-image-upload.js, and add the following code:
```javascript
import Vue from 'vue'
import ImageUploader from 'vue-image-upload-resize'

Vue.use(ImageUploader)
```
2. In your nuxt.config.js, add the client plugin:
```javascript
export default {
  // ... other config
  plugins: [
    { src: '~/plugins/vue-image-upload.js', mode: 'client' },
  ]
}
```
3. When you use the componenent inside a page, make sure to wrap it in <client-only> tags (<no-ssr> in v < 2.9.0, docs).
```javascript
<template>
  <client-only>
    <image-uploader
      :debug="1"
    ></image-uploader>
 </client-only>
</template>
```

**Comment by Pranavraut033** [comment]
Thanks! @KerneggerTim I guess I missed reading that 😅. Thank you for being helpful.
