### ISSUE TITLE
Overriding the default <input type="file"> box and text?

### ISSUE THREAD

**Issue by gorbypark** [kartoteket/vue-image-upload-resize#6]
This is more of a support request than an issue, sorry if this is the wrong space for it...I'm attempting to use the [`vuetify-upload-button`](https://github.com/doritobandito/vuetify-upload-button) component to select the image for upload.  Below is the code I'm trying.  Any ideas?  I've tried a number of variations, such as setting `<upload-btn class="fileupload">` and `:className="fileupload"` etc, but I can't seem to get it to work.
```
<td>
  <image-uploader
    :debug="2"
    :quality=".7"
    :autoRotate=true
    outputFormat="base64"
    :preview=true
    :className="upload-btn"
    capture="environment"
  >
  </image-uploader>
  <upload-btn></upload-btn>
</td>
```

I end up with both buttons, and the "upload" button doesn't actually interface with the component.
![select](https://user-images.githubusercontent.com/19569469/44621975-bd3eb700-a864-11e8-8544-a44c73ea9b27.png)

**Comment by svale** [comment]
Hi,

I'm not at all sure if these two components can play nice together. They seem to overlap a bit. As far as I can see, you will be injecting two input-fields to your markup...

However, if you want to inject your custom button to 'vue-image-upload-resize', you should use the input label slot. As in

```
<image-uploader ... >
	<label for="fileInput" slot="upload-label">
			<!-- custom markup -->
			<upload-btn></upload-btn>
		</label>
	<image-uploader>
```	

And then hide the input as per https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

**Comment by svale** [comment]
Hope you figured this out. Feel free to re-open if needed
