### ISSUE TITLE
Fail to import

### ISSUE THREAD

**Issue by mhpm** [kartoteket/vue-image-upload-resize#8]
![image](https://user-images.githubusercontent.com/32468301/49890450-b2a33000-fe09-11e8-9229-26c616333024.png)
v

![image](https://user-images.githubusercontent.com/32468301/49890472-c2bb0f80-fe09-11e8-87e5-c79c32c5ee97.png)

always give me this error, please help

![image](https://user-images.githubusercontent.com/32468301/49890513-dbc3c080-fe09-11e8-8fa8-88a94aa236cc.png)

**Comment by svale** [comment]
Sorry, I've neglected to update the readme properly. 

The correct use from v2 should be to import and initialise  in your entry-point file (typically main.js), like so:
```js
import Vue from 'vue'
...
import ImageUploader from 'vue-image-upload-resize'
Vue.use(ImageUploader)
...
new Vue({
  render: h => h(App),
}).$mount('#app')
```
Then you should be able to use `<image-uploader> </image-uploader>` in any component.

Does this work?

I'll fix the Readme asap...

**Comment by svale** [comment]
@mhpm I also put together a quick demo on https://codesandbox.io/s/mqnow97omj Maybe that can be helpful. 

Please feel free to re-open if this is not the right solution.

**Comment by mhpm** [comment]
@svale Thank you so much my friend! **it already works!** **that solved my problem!**

**Comment by mhpm** [comment]
Please update the **README.md** on github too! i still see the old version!

**Comment by svale** [comment]
:-) Done!
